# Generated by Django 3.1.5 on 2021-01-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animelist', '0002_auto_20210122_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='password',
            new_name='name',
        ),
    ]
